routes/web.php
<?php

use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InfoUserController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ResetController;
use App\Http\Controllers\SessionsController;

use App\Http\Controllers\PelajarControllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PengajarController;
use App\Http\Controllers\PengajarAkunController;
use App\Http\Controllers\PelatihanController;
use App\Http\Controllers\PelajarController;
use App\Http\Controllers\levelingController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\KelasPelajarController;
use App\Http\Controllers\PembayaranAdminController;
use App\Http\Controllers\PembayaranController;
use App\Http\Controllers\pelajarPembayaranController;
use App\Http\Controllers\pengaturanAdminController;
use App\Http\Controllers\KelasPengajarController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\DetailNilaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'auth'], function () {

	Route::resource('pengajar', PengajarController::class);
	Route::resource('pengajarAkun', PengajarAkunController::class);
	Route::resource('pelatihan', PelatihanController::class);
	Route::resource('pelajar', PelajarController::class);
	Route::resource('kelas', KelasController::class);
	Route::resource('kelasPelajar', KelasPelajarController::class);
	Route::resource('pembayaranAdmin', PembayaranAdminController::class);
	Route::resource('pembayaran', PembayaranController::class);
	Route::resource('pelajarPembayaran', pelajarPembayaranController::class);
	Route::resource('pengaturanAdmin', pengaturanAdminController::class);
	Route::resource('kelasPengajar', KelasPengajarController::class);
	Route::resource('jadwal', jadwalController::class);
	Route::resource('nilai', NilaiController::class);
	Route::resource('detailNilai', DetailNilaiController::class);

	Route::get('leveling', [LevelingController::class, 'home']);

	Route::get('dashboardAdmin', function () {
		return view('dashboardAdmin');
	})->name('dashboardAdmin');

	Route::get('dashboardPengajar', function () {
		return view('dashboardPengajar');
	})->name('dashboardPengajar');

	Route::get('dashboardPelajar', function () {
		return view('dashboardPelajar');
	})->name('dashboardPelajar');

	Route::get('pelatihanPengajar', function () {
		return view('pengajars/pelatihanPengajar');
	})->name('pelatihanPengajar');
	
    Route::get('/', [HomeController::class, 'home']);
	Route::get('dashboard', function () {
		return view('dashboard');
	})->name('dashboard');

	Route::get('billing', function () {
		return view('billing');
	})->name('billing');	

	Route::get('profile', function () {
		return view('profile');
	})->name('profile');

	Route::get('rtl', function () {
		return view('rtl');
	})->name('rtl');

	Route::get('user-management', function () {
		return view('laravel-examples/user-management');
	})->name('user-management');

	Route::get('tables', function () {
		return view('tables');
	})->name('tables');

    Route::get('virtual-reality', function () {
		return view('virtual-reality');
	})->name('virtual-reality');

    Route::get('static-sign-in', function () {
		return view('static-sign-in');
	})->name('sign-in');

    Route::get('static-sign-up', function () {
		return view('static-sign-up');
	})->name('sign-up');

    Route::get('/logout', [SessionsController::class, 'destroy']);
	Route::get('/user-profile', [InfoUserController::class, 'create']);
	Route::post('/user-profile', [InfoUserController::class, 'store']);
    Route::get('/login', function () {
		return view('dashboard');
	})->name('sign-up');
});



Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', [RegisterController::class, 'create']);
    Route::post('/register', [RegisterController::class, 'store']);
    Route::get('/login', [SessionsController::class, 'create']);
    Route::post('/session', [SessionsController::class, 'store']);
	Route::get('/login/forgot-password', [ResetController::class, 'create']);
	Route::post('/forgot-password', [ResetController::class, 'sendEmail']);
	Route::get('/reset-password/{token}', [ResetController::class, 'resetPass'])->name('password.reset');
	Route::post('/reset-password', [ChangePasswordController::class, 'changePassword'])->name('password.update');

});

Route::get('/login', function () {
    return view('session/login-session');
})->name('login');

resources/views/admins/editPembayaranAdmin.blade.php
@extends('layouts.user_type.auth')

@section('content')

  <main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="container">
                <div class="row mt-4">
                    <div class="col-sm">
                        <h6>Pembayaran Berhasil </h6>
                    </div>
                </div>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Pelatihan</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Pelajar</th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php $pembayarans = DB::table('pembayarans')
                        ->join('pelatihans', 'pembayarans.kd_pelatihan', '=', 'pelatihans.id')
                        ->join('pelajars', 'pembayarans.kd_pelajar', '=', 'pelajars.kd_pelajar')
                        ->select('pembayarans.*', 'pelatihans.nm_pelatihan', 'pelajars.nm_pelajar')
                        ->where('pembayarans.id', '=', $pembayaran->id)
                        ->get(); ?>

                    @foreach ($pembayarans as $pembayaran)
                        
                            <tr>
                        <td>
                            <div class="d-flex px-2 py-1">
                            <div>
                                
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ $pembayaran->nm_pelatihan }}</h6>
                            </div>
                            </div>
                        </td>
                        <td class="align-middle text-center">
                            <label class="text-xs font-weight-bold mb-0" >{{ $pembayaran->nm_pelajar }}</label>
                        </td>
                        </tr>
                          
                  </tbody>
                </table>
                <h6 class="mb-0 text-sm p-3">Bukti Transfer</h6>
                <img src="/image/{{ $pembayaran->image }}" class="p-3" width="500px">

                <?php $pengajars = DB::table('pelatihans')
                        ->join('pengajars', 'pelatihans.kd_pengajar', '=', 'pengajars.id')
                        ->where('pelatihans.id', '=', $pembayaran->kd_pelatihan)
                        ->select('pelatihans.*')
                        ->get(); ?>
                
                @foreach ($pengajars as $pengajar)

                <form action="{{ route('pembayaran.update',$pembayaran->id, $pengajar->kd_pengajar) }}" method="POST" enctype="multipart/form-data"> 
                    @csrf
                    @method('PUT')
<<<<<<< HEAD
                    <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pelatihan" value="{{ $pengajar->id }}" readonly>
                    <button type="submit" id="status" name="status" value="berhasil" class=" btn btn-primary shadow-none text-dark" style="margin-left:20px;">BENAR</button>
=======
                    <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pengajar" value="{{ $pengajar->kd_pengajar }}" readonly>
                    <button type="submit" id="status" name="status" value="berhasil" class=" btn btn-dark shadow-none text-primary" style="margin-left:20px;">SETUJU</button>
                    <button type="submit" id="status" name="status" value="tidaksetuju" class=" btn btn-dark shadow-none text-primary" style="margin-left:20px;">TIDAK SETUJU</button>
>>>>>>> 740cc167410b68f4844385af0f4d50612c964346
                </form>
                    @endforeach
                    @endforeach
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  
  @endsection

resources/views/admins/pembayaranAdmin.blade.php
@extends('layouts.user_type.auth')

@section('content')

  <main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-6">
          <div class="card mb-4">
            <div class="container">
                <div class="row mt-4">
                    <div class="col-sm">
                        <h6>Pembayaran Berhasil </h6>
                    </div>
                </div>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Pelatihan</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Pelajar</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php $pembayarans = DB::table('pembayarans')
                        ->join('pelatihans', 'pembayarans.kd_pelatihan', '=', 'pelatihans.id')
                        ->join('pelajars', 'pembayarans.kd_pelajar', '=', 'pelajars.kd_pelajar')
                        ->select('pembayarans.*', 'pelatihans.nm_pelatihan', 'pelajars.nm_pelajar')
                        ->where('pembayarans.status', '=', 'berhasil')
                        ->get(); ?>

                    @foreach ($pembayarans as $pembayaran)
                        
                            <tr>
                        <td>
                            <div class="d-flex px-2 py-1">
                            <div>
                                <img src="/image/{{ $pembayaran->image }}" class="avatar avatar-sm me-3" alt="user1">
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ $pembayaran->nm_pelatihan }}</h6>
                            </div>
                            </div>
                        </td>
                        <td class="align-middle text-center">
                            <label class="text-xs font-weight-bold mb-0" >{{ $pembayaran->nm_pelajar }}</label>
                        </td>
                        <td class="align-middle text-center">
                          <!-- {{$pembayaran->id}} -->
                        <a class="text-xs font-weight-bold mb-0" href="{{ route('detailNilai.show',$pembayaran->id) }}">Detail</a>
                        </td>
                        </tr>
                          
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="col-6">
          <div class="card mb-4">
            <div class="container">
                <div class="row mt-4">
                    <div class="col-sm">
                        <h6>Pembayaran Tertunda </h6>
                    </div>
                </div>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Pelatihan</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Pelajar</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php $pembayarans = DB::table('pembayarans')
                        ->join('pelatihans', 'pembayarans.kd_pelatihan', '=', 'pelatihans.id')
                        ->join('pelajars', 'pembayarans.kd_pelajar', '=', 'pelajars.kd_pelajar')
                        ->select('pembayarans.*', 'pelatihans.nm_pelatihan', 'pelajars.nm_pelajar')
                        ->where('pembayarans.status', '!=', 'berhasil')
                        ->where('pembayarans.image', '!=', '')
                        ->get(); ?>

                    @foreach ($pembayarans as $pembayaran)
                        
                            <tr>
                        <td>
                            <div class="d-flex px-2 py-1">
                            <div>
                                
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ $pembayaran->nm_pelatihan }}</h6>
                            </div>
                            </div>
                        </td>
                        <td class="align-middle text-center">
                            <label class="text-xs font-weight-bold mb-0" >{{ $pembayaran->nm_pelajar }}</label>
                        </td>
                        <td class="align-middle text-center">
                            <a class="text-suces font-weight-bold mb-0" href="{{ route('pembayaran.edit',$pembayaran->id) }}">Detail</a>
                        </td>
                        </tr>
                          
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  
  @endsection

resources/views/admins/pengaturanAdmin.blade.php
@extends('layouts.user_type.auth')

@section('content')

<?php 
  $dashboards = DB::table('dashboards')->get();  
?>

<div class="col-lg-12 mb-4">
    <div class="card  p-3">
    @foreach ($dashboards as $dashboard)
      <div class="overflow-hidden position-relative border-radius-lg bg-cover " style="background-image: url('/image/{{ $dashboard->image }}'); height:400px;">
      </div>
    </div>
  </div>
  {{$dashboard->id}}
<form action="{{ route('pengaturanAdmin.update', 1) }}" method="POST" enctype="multipart/form-data">
  @csrf
  @method('PUT')
  <label>Gambar</label><br>
  <input type="file" name="image" class="form-control" placeholder="images">
  <div class="text-center">
    <button type="submit" class="btn btn-dark w-100 mt-4 mb-0" >Daftar</button>
  </div>
</form>

@endforeach

@endsection