routes/web.php
<?php

use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InfoUserController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ResetController;
use App\Http\Controllers\SessionsController;

use App\Http\Controllers\PelajarControllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PengajarController;
use App\Http\Controllers\PengajarAkunController;
use App\Http\Controllers\PelatihanController;
use App\Http\Controllers\PelajarController;
use App\Http\Controllers\levelingController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\KelasPelajarController;
use App\Http\Controllers\PembayaranAdminController;
use App\Http\Controllers\PembayaranController;
use App\Http\Controllers\pelajarPembayaranController;
use App\Http\Controllers\pengaturanAdminController;
use App\Http\Controllers\KelasPengajarController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\DetailNilaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'auth'], function () {

	Route::resource('pengajar', PengajarController::class);
	Route::resource('pengajarAkun', PengajarAkunController::class);
	Route::resource('pelatihan', PelatihanController::class);
	Route::resource('pelajar', PelajarController::class);
	Route::resource('kelas', KelasController::class);
	Route::resource('kelasPelajar', KelasPelajarController::class);
	Route::resource('pembayaranAdmin', PembayaranAdminController::class);
	Route::resource('pembayaran', PembayaranController::class);
	Route::resource('pelajarPembayaran', pelajarPembayaranController::class);
	Route::resource('pengaturanAdmin', pengaturanAdminController::class);
	Route::resource('kelasPengajar', KelasPengajarController::class);
	Route::resource('jadwal', jadwalController::class);
	Route::resource('nilai', NilaiController::class);
	Route::resource('detailNilai', DetailNilaiController::class);

	Route::get('leveling', [LevelingController::class, 'home']);

	Route::get('dashboardAdmin', function () {
		return view('dashboardAdmin');
	})->name('dashboardAdmin');

	Route::get('dashboardPengajar', function () {
		return view('dashboardPengajar');
	})->name('dashboardPengajar');

	Route::get('dashboardPelajar', function () {
		return view('dashboardPelajar');
	})->name('dashboardPelajar');

	Route::get('pelatihanPengajar', function () {
		return view('pengajars/pelatihanPengajar');
	})->name('pelatihanPengajar');
	
    Route::get('/', [HomeController::class, 'home']);
	Route::get('dashboard', function () {
		return view('dashboard');
	})->name('dashboard');

	Route::get('billing', function () {
		return view('billing');
	})->name('billing');	

	Route::get('profile', function () {
		return view('profile');
	})->name('profile');

	Route::get('rtl', function () {
		return view('rtl');
	})->name('rtl');

	Route::get('user-management', function () {
		return view('laravel-examples/user-management');
	})->name('user-management');

	Route::get('tables', function () {
		return view('tables');
	})->name('tables');

    Route::get('virtual-reality', function () {
		return view('virtual-reality');
	})->name('virtual-reality');

    Route::get('static-sign-in', function () {
		return view('static-sign-in');
	})->name('sign-in');

    Route::get('static-sign-up', function () {
		return view('static-sign-up');
	})->name('sign-up');

    Route::get('/logout', [SessionsController::class, 'destroy']);
	Route::get('/user-profile', [InfoUserController::class, 'create']);
	Route::post('/user-profile', [InfoUserController::class, 'store']);
    Route::get('/login', function () {
		return view('dashboard');
	})->name('sign-up');
});



Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', [RegisterController::class, 'create']);
    Route::post('/register', [RegisterController::class, 'store']);
    Route::get('/login', [SessionsController::class, 'create']);
    Route::post('/session', [SessionsController::class, 'store']);
	Route::get('/login/forgot-password', [ResetController::class, 'create']);
	Route::post('/forgot-password', [ResetController::class, 'sendEmail']);
	Route::get('/reset-password/{token}', [ResetController::class, 'resetPass'])->name('password.reset');
	Route::post('/reset-password', [ChangePasswordController::class, 'changePassword'])->name('password.update');

});

Route::get('/login', function () {
    return view('session/login-session');
})->name('login');

app/Models/Pelajar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pelajar extends Model
{
    use HasFactory;

    protected $fillable = [
        'nm_pelajar', 'alamat', 'kota', 'tmpt_lahir', 'tgl_lahir', 'jns_kelamin', 'no_telp', 'image', 'kd_pelajar'
    ];
}

app/Http/Controllers/PelajarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pelajar;
use Illuminate\Http\Request;

class PelajarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pelajars = Pelajar::latest()->paginate(5);
    
        return view('pelajars.index',compact('pelajars'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pelajars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nm_pelajar' => 'required',
            'alamat' => 'required',
            'kd_pelajar' => 'required',
            'kota' => 'required',
            'tmpt_lahir' => 'required',
            'tgl_lahir' => 'required',
            'jns_kelamin' => 'required',
            'no_telp' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
  
        $input = $request->all();
  
        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }
    
        Pelajar::create($input);
     
        return redirect('/leveling');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pelajar  $pelajar
     * @return \Illuminate\Http\Response
     */
    public function show(Pelajar $pelajar)
    {
        return view('pelajars.show',compact('pelajar'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pelajar  $pelajar
     * @return \Illuminate\Http\Response
     */
    public function edit(Pelajar $pelajar)
    {
        return view('pelajars.edit',compact('pelajar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pelajar  $pelajar
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pelajar $pelajar)
    {
        $request->validate([
            'nm_pelajar' => 'required',
            'alamat' => 'required',
            'kota' => 'required',
            'tmpt_lahir' => 'required',
            'kd_pelajar' => 'required',
            'tgl_lahir' => 'required',
            'jns_kelamin' => 'required',
            'no_telp' => 'required',
        ]);
  
        $input = $request->all();
  
        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }else{
            unset($input['image']);
        }
          
        $pelajar->update($input);
    
        return redirect()->route('pelajar.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pelajar  $pelajar
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pelajar $pelajar)
    {
        $pelajar->delete();
     
        return redirect()->route('pelajar.index');

    }
}

resources/views/pelajars/create.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Tambah Pelajar</h6>
                    </div>
                    <?php
        $kd_pengajars = DB::table('users')
                    ->latest()
                    ->limit(1)
                        ->get(); ?>

                    <form action="{{ route('pelajar.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-sm">
                            @foreach ($kd_pengajars as $kd_pengajar)
                        
                            <label>Kd Pelajar</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelajar" name="kd_pelajar" value="{{$kd_pengajar->id}}" readonly>
                        
                        
                                <label>Nama Pelajar</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelajar" name="nm_pelajar" value="{{$kd_pengajar->name}}">
                                @endforeach
                                <label>Alamat</label>
                                <textarea type="text" class="form-control mb-3" placeholder="Alamat" name="alamat" rows="4"></textarea>
                                
                                <label>Kota</label>
                                <input type="text" class="form-control mb-3" placeholder="Kota" name="kota">

                                <label>Tempat Lahir</label>
                                <input type="text" class="form-control mb-3" placeholder="Tempat Lahir" name="tmpt_lahir">
                            </div>
                            <div class="col-sm">
                                <label>Tanggal Lahir</label>
                                <input type="date" class="form-control mb-3" placeholder="Tanggal Lahir" name="tgl_lahir">

                                <label>Jenis kelamin</label>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm">
                                            <input type="radio" id="L" name="jns_kelamin" value="L">
                                            <label for="L">Laki - Laki</label><br>
                                        </div>
                                        <div class="col-sm">
                                            <input type="radio" id="P" name="jns_kelamin" value="P">
                                            <label for="P">Perempuan</label>
                                        </div>
                                        <div class="col-sm">
                                        </div>
                                    </div>
                                </div>

                                <label>No Telepon</label>
                                <input type="tel" class="form-control mb-3" placeholder="No Telepon" name="no_telp">
                                
                                <label>Gambar</label>
                                <input type="file" name="image" class="form-control" placeholder="image">
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-dark w-100 mt-4 mb-0">Daftar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</main>

@endsection

resources/views/pelajars/detailKelas.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Tambah Pelatihan Saya</h6>
                    </div>
                    <?php $pelatihans = DB::table('pelatihans')
                        ->join('pengajars', 'pelatihans.kd_pengajar','=','pengajars.id')
                        ->select('pelatihans.*','pengajars.nm_pengajar')
                        ->where('pelatihans.id', '=', $pelatihan)
                        ->get(); ?>

                    @foreach ($pelatihans as $pembayaran)

                    <form action="{{ route('kelasPelajar.store',$pembayaran->id) }}" method="POST" enctype="multipart/form-data"> 
                    @csrf
                        <div class="row">
                            <div class="col-sm">
                                <label>Nama Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="nm_pelatihan" value="{{ $pembayaran->nm_pelatihan }}" readonly>

                                <label>Nama Pengajar</label>
                                <input type="text" class="form-control mb-3" placeholder="Biaya Pelatihan" name="biaya_pelatihan" value="{{ $pembayaran->nm_pengajar }}" readonly>

                                <label>Biaya Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Biaya Pelatihan" name="biaya_pelatihan" value="{{ $pembayaran->biaya_pelatihan }}" readonly>
                            </div>
                            <div class="col-sm">
                                <label>Jadwal</label>
                                <input type="date" class="form-control mb-3" placeholder="jadwal" name="jadwal" value="{{ $pembayaran->jadwal }}" readonly>
                                
                                <label>Gambar</label>
                                <input type="file" name="image" class="form-control mb-3" placeholder="image" readonly>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pelatihan" value="{{ $pembayaran->id }}" readonly>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pelajar" value="{{ auth()->user()->id }}" readonly>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pengajar" value="{{$pembayaran->kd_pengajar }}" readonly>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="status" value="gagal" readonly>
                            </div>
                        </div>
                        <!-- {{auth()->user()->id}} -->
                        <!-- {{$pelatihan}} -->
                        <?php $cek_data = DB::table('pembayarans')
                        ->join('pelatihans', 'pembayarans.kd_pelatihan','=','pelatihans.id')
<<<<<<< HEAD
                        ->join('pelajars', 'pembayarans.kd_pelajar','=','pelajars.id')
                        ->where('pelajars.id', '=', auth()->user()->id)
=======
                        ->join('pelajars', 'pembayarans.kd_pelajar','=','pelajars.kd_pelajar')
                        ->where('pelajars.kd_pelajar', '=', auth()->user()->id)
>>>>>>> 740cc167410b68f4844385af0f4d50612c964346
                        ->where('pelatihans.id', '=', $pelatihan)
                        ->get(); 
                        // echo $cek_data;
                        if(count($cek_data)>0){
                            echo('
                            <a href="/file/'.$pembayaran->materi.'"  class="btn btn-dark w-100 mt-4 mb-4 mb-0" download>Download Materi</a>
                            <button type="readonly" class="btn btn-dark w-100  mb-0" disabled>Anda telah mengambil kelas ini</button>') ;
                        } else {
                            echo('
                            <div class="text-center">
                            <button type="submit" class="btn btn-dark w-100 mt-4 mb-0">Tambah Kelas</button>
                        </div>
                            ');
                        }
                        
                        ?>
                    </form>

                    @endforeach
                </div>
            </div>
        </div>
    </div>

</main>

@endsection

resources/views/pelajars/detailNilai.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Pelatihan Saya</h6>
                    </div>
                    {{auth()->user()->level}}
                    <?php 
                    if(auth()->user()->level=="admin"){
                        $pelatihans = DB::table('pelatihans')
                        ->join('pengajars', 'pelatihans.kd_pengajar','=','pengajars.id')
                        ->join('pembayarans', 'pelatihans.id','=','pembayarans.kd_pelatihan')
                        ->where('pembayarans.id', '=', $pelatihan)
                        ->get(); 
                    } else {
                        $pelatihans = DB::table('pelatihans')
                        ->join('pengajars', 'pelatihans.kd_pengajar','=','pengajars.id')
                        ->join('pembayarans', 'pelatihans.id','=','pembayarans.kd_pelatihan')
                        ->where('pelatihans.id', '=', $pelatihan)
                        ->where('pembayarans.kd_pelajar', '=', auth()->user()->id)
                        ->get(); }?>
                    

                    @foreach ($pelatihans as $pembayaran)   

                    <form action="{{ route('kelasPelajar.store',$pembayaran->id) }}" method="POST" enctype="multipart/form-data"> 
                    @csrf
                        <div class="row">
                            <div class="col-sm">
                                <label>Nama Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="nm_pelatihan" value="{{ $pembayaran->nm_pelatihan }}" readonly>

                                <label>Nama Pengajar</label>
                                <input type="text" class="form-control mb-3" placeholder="Biaya Pelatihan" name="biaya_pelatihan" value="{{ $pembayaran->nm_pengajar }}" readonly>

                                <label>Biaya Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Biaya Pelatihan" name="biaya_pelatihan" value="{{ $pembayaran->biaya_pelatihan }}" readonly>
                            </div>
                            <div class="col-sm">
                                <label>Jadwal</label>
                                <input type="date" class="form-control mb-3" placeholder="jadwal" name="jadwal" value="{{ $pembayaran->jadwal }}" readonly>
                                
                                <label>Gambar</label>
                                <input type="file" name="image" class="form-control mb-3" placeholder="image" readonly>
                                <input type="hidden" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pelatihan" value="{{ $pembayaran->id }}" readonly>
                                <input type="hidden" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pelajar" value="{{ auth()->user()->id }}" readonly>
                                <input type="hidden" class="form-control mb-3" placeholder="Nama Pelatihan" name="kd_pengajar" value="{{$pembayaran->kd_pengajar }}" readonly>
                                <input type="hidden" class="form-control mb-3" placeholder="Nama Pelatihan" name="status" value="gagal" readonly>
                            </div>
                    </form>
                    <!-- <?php print_r($pembayaran); ?> -->
                    <!-- {{$pembayaran->id}} -->
                    <?php if(auth()->user()->level == "admin"){ ?> 
                                <form action="{{ route('detailNilai.update', $pembayaran->id) }}" method="POST" enctype="multipart/form-data">
  @csrf
  @method('PUT')
  <label>Sertifikat</label><br>
  <input type="file" name="sertifikat" class="form-control" placeholder="sertifikats">
  <div class="text-center">
    <button type="submit" class="btn btn-dark w-100 mt-4 mb-0" >Upload</button>
  </div>
</form>
                            <?php } else { ?>
                                <img src="/image/{{ $pembayaran->sertifikat }}" class="p-3" width="200px">
                                <div class="text-center">
                                <a href="/image/{{ $pembayaran->sertifikat }}"  class="btn btn-dark w-100 mt-4 mb-4 mb-0" download>Download Sertifikat</a>
                                <a >Anda dapat mengambil sertifikat yg asli di kantor cabang terdekat</a>
                        </div>
                            <?php } ?>
                        </div>

                    @endforeach
                </div>
            </div>
        </div>
    </div>

</main>

@endsection

resources/views/pelajars/edit.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Tambah Pelajar</h6>
                    </div>
                    <form action="{{ route('pelajar.update',$pelajar->id) }}" method="POST" enctype="multipart/form-data"> 
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-sm">
                                <label>Nama Pelajar</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelajar" name="nm_pelajar" value="{{ $pelajar->nm_pelajar }}">

                                <label>Alamat</label>
                                <textarea type="text" class="form-control mb-3" placeholder="Alamat" name="alamat" rows="4">{{ $pelajar->alamat }}</textarea>
                                
                                <label>Kota</label>
                                <input type="text" class="form-control mb-3" placeholder="Kota" name="kota" value="{{ $pelajar->kota }}">

                                <label>Tempat Lahir</label>
                                <input type="text" class="form-control mb-3" placeholder="Tempat Lahir" name="tmpt_lahir" value="{{ $pelajar->tmpt_lahir }}">
                            </div>
                            <div class="col-sm">
                                <label>Tanggal Lahir</label>
                                <input type="date" class="form-control mb-3" placeholder="Tanggal Lahir" name="tgl_lahir"  value="{{ $pelajar->tgl_lahir }}">

                                <label>Jenis kelamin</label>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm">
                                            <?php if($pelajar->jns_kelamin=="L"){?>
                                            <input type="radio" id="L" name="jns_kelamin" value="L" checked><?php } else {?>
                                            <input type="radio" id="L" name="jns_kelamin" value="L" > <?php } ?>
                                            <label for="L">Laki - Laki</label><br>
                                        </div>
                                        <div class="col-sm">
                                            <?php if($pelajar->jns_kelamin=="P"){?>
                                            <input type="radio" id="P" name="jns_kelamin" value="P" checked><?php } else {?>
                                            <input type="radio" id="P" name="jns_kelamin" value="P" > <?php } ?>
                                            <label for="L">Perempuan</label><br>
                                        </div>
                                        <div class="col-sm">
                                        </div>
                                    </div>
                                </div>

                                <label>No Telepon</label>
                                <input type="tel" class="form-control mb-3" placeholder="No Telepon" name="no_telp" value="{{ $pelajar->no_telp }}">
                                
                                <label>Gambar</label><br>
                                <img src="/image/{{ $pelajar->image }}" width="300px">
                                <input type="file" name="image" class="form-control" placeholder="image">
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-dark w-100 mt-4 mb-0">Ubah</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</main>

@endsection

resources/views/pelajars/index.blade.php
@extends('layouts.user_type.auth')

@section('content')

  <main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="container">
                <div class="row mt-4">
                    <div class="col-sm">
                        <h6>Daftar Pelajar</h6>
                    </div>
                </div>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Pelajar</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Alamat</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">No Telp</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Pengaturan</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($pelajars as $pelajar)
                        <tr>
                        <td>
                            <div class="d-flex px-2 py-1">
                            <div>
                                <img src="/image/{{ $pelajar->image }}" class="avatar avatar-sm me-3" alt="user1">
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ $pelajar->nm_pelajar }}</h6>
                                <p class="text-xs text-secondary mb-0">pelajar</p>
                            </div>
                            </div>
                        </td>
                        <td>
                            <p class="text-xs font-weight-bold mb-0">{{ $pelajar->alamat }}</p>
                        </td>
                        <td class="align-middle text-center text-sm">
                            <p class="text-xs font-weight-bold mb-0">{{ $pelajar->no_telp }}</p>
                        </td>
                        <td class="align-middle text-center">
                            <form action="{{ route('pelajar.destroy',$pelajar->id) }}" method="POST">
                                <a class="btn btn-primary shadow-none text-dark" href="{{ route('pelajar.edit',$pelajar->id) }}" style="width:60px;">Edit</a>

                                @csrf
                                @method('DELETE')

                                <button type="submit" class=" btn btn-primary shadow-none text-danger" style="margin-left:20px;">Delete</button>
                            </form>
                        </td>
                        </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  
  @endsection

resources/views/pelajars/uploadBuktiPembayaran.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Upload Bukti Pembayaran</h6>
                    </div>

                    <?php $pembayarans = DB::table('pembayarans') 
                        ->where('id','=',$dashboard)
                        ->get(); ?>
                        
                    @foreach ($pembayarans as $pembayaran)
                    {{$pembayaran->id}}
                    <form action="{{ route('pelajarPembayaran.update', $pembayaran->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <label>Gambar</label><br>
                    <input type="file" name="image" class="form-control" placeholder="images">
                    <div class="text-center">
                        <button type="submit" id="upload" name="status" value="upload" class=" btn btn-dark w-100 mt-4 mb-0" >BENAR</button>
                    </div>
                    </form>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

</main>

@endsection