routes/web.php
<?php

use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InfoUserController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ResetController;
use App\Http\Controllers\SessionsController;

use App\Http\Controllers\PelajarControllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PengajarController;
use App\Http\Controllers\PengajarAkunController;
use App\Http\Controllers\PelatihanController;
use App\Http\Controllers\PelajarController;
use App\Http\Controllers\levelingController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\KelasPelajarController;
use App\Http\Controllers\PembayaranAdminController;
use App\Http\Controllers\PembayaranController;
use App\Http\Controllers\pelajarPembayaranController;
use App\Http\Controllers\pengaturanAdminController;
use App\Http\Controllers\KelasPengajarController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\DetailNilaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'auth'], function () {

	Route::resource('pengajar', PengajarController::class);
	Route::resource('pengajarAkun', PengajarAkunController::class);
	Route::resource('pelatihan', PelatihanController::class);
	Route::resource('pelajar', PelajarController::class);
	Route::resource('kelas', KelasController::class);
	Route::resource('kelasPelajar', KelasPelajarController::class);
	Route::resource('pembayaranAdmin', PembayaranAdminController::class);
	Route::resource('pembayaran', PembayaranController::class);
	Route::resource('pelajarPembayaran', pelajarPembayaranController::class);
	Route::resource('pengaturanAdmin', pengaturanAdminController::class);
	Route::resource('kelasPengajar', KelasPengajarController::class);
	Route::resource('jadwal', jadwalController::class);
	Route::resource('nilai', NilaiController::class);
	Route::resource('detailNilai', DetailNilaiController::class);

	Route::get('leveling', [LevelingController::class, 'home']);

	Route::get('dashboardAdmin', function () {
		return view('dashboardAdmin');
	})->name('dashboardAdmin');

	Route::get('dashboardPengajar', function () {
		return view('dashboardPengajar');
	})->name('dashboardPengajar');

	Route::get('dashboardPelajar', function () {
		return view('dashboardPelajar');
	})->name('dashboardPelajar');

	Route::get('pelatihanPengajar', function () {
		return view('pengajars/pelatihanPengajar');
	})->name('pelatihanPengajar');
	
    Route::get('/', [HomeController::class, 'home']);
	Route::get('dashboard', function () {
		return view('dashboard');
	})->name('dashboard');

	Route::get('billing', function () {
		return view('billing');
	})->name('billing');	

	Route::get('profile', function () {
		return view('profile');
	})->name('profile');

	Route::get('rtl', function () {
		return view('rtl');
	})->name('rtl');

	Route::get('user-management', function () {
		return view('laravel-examples/user-management');
	})->name('user-management');

	Route::get('tables', function () {
		return view('tables');
	})->name('tables');

    Route::get('virtual-reality', function () {
		return view('virtual-reality');
	})->name('virtual-reality');

    Route::get('static-sign-in', function () {
		return view('static-sign-in');
	})->name('sign-in');

    Route::get('static-sign-up', function () {
		return view('static-sign-up');
	})->name('sign-up');

    Route::get('/logout', [SessionsController::class, 'destroy']);
	Route::get('/user-profile', [InfoUserController::class, 'create']);
	Route::post('/user-profile', [InfoUserController::class, 'store']);
    Route::get('/login', function () {
		return view('dashboard');
	})->name('sign-up');
});



Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', [RegisterController::class, 'create']);
    Route::post('/register', [RegisterController::class, 'store']);
    Route::get('/login', [SessionsController::class, 'create']);
    Route::post('/session', [SessionsController::class, 'store']);
	Route::get('/login/forgot-password', [ResetController::class, 'create']);
	Route::post('/forgot-password', [ResetController::class, 'sendEmail']);
	Route::get('/reset-password/{token}', [ResetController::class, 'resetPass'])->name('password.reset');
	Route::post('/reset-password', [ChangePasswordController::class, 'changePassword'])->name('password.update');

});

Route::get('/login', function () {
    return view('session/login-session');
})->name('login');

app/Models/Pelatihan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pelatihan extends Model
{
    use HasFactory;

    protected $fillable = [
        'nm_pelatihan','kd_pengajar','biaya_pelatihan','jadwal','image', 'materi'
    ];
}

app/Http/Controllers/PelatihanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pelatihan;
use App\Models\Pengajar;
use Illuminate\Http\Request;

class PelatihanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pelatihans = Pelatihan::latest()->paginate(5);
    
        return view('pelatihans.index',compact('pelatihans'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pengajars = Pengajar::latest()->paginate(5);
        
        return view('pelatihans.create',compact('pengajars'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nm_pelatihan' => 'required',
            'kd_pengajar' => 'required',
            'biaya_pelatihan' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
  
        $input = $request->all();
  
        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }
    
        Pelatihan::create($input);
     
        return redirect()->route('pelatihan.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pelatihan  $pelatihan
     * @return \Illuminate\Http\Response
     */
    public function show(Pelatihan $pelatihan)
    {
        return view('pelajars.detailKelas',compact('pelatihan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pelatihan  $pelatihan
     * @return \Illuminate\Http\Response
     */
    public function edit(Pelatihan $pelatihan)
    {
        // echo $pelatihan;
        return view('pelatihans.edit',compact('pelatihan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pelatihan  $pelatihan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pelatihan $pelatihan)
    {
        // echo $pelatihan;
        $request->validate([
            'nm_pelatihan' => 'required',
            'kd_pengajar' => 'required',
            'biaya_pelatihan' => 'required',
            'jadwal' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $input = $request->all();
  
        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }else{
            unset($input['image']);
        }
          
        $pelatihan->update($input);
    
        return redirect()->route('pelatihan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pelatihan  $pelatihan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pelatihan $pelatihan)
    {
        unlink(public_path().'/image/'.$pelatihan->image);
        $pelatihan->delete();
     
        return redirect()->route('pelatihan.index');
    }
}

resources/views/pelatihans/create.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Tambah Pelatihan</h6>
                    </div>
                    <form action="{{ route('pelatihan.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-sm">
                                <label>Nama Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="nm_pelatihan">

                                <label>Nama Pengajar</label>
                                <!-- <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="nm_pengajar"> -->
                                <select class="form-control mb-3" name="kd_pengajar">
                                    @foreach ($pengajars as $pengajar)
                                        <option value="{{ $pengajar->id }}">{{ $pengajar->nm_pengajar }}</option>
                                    @endforeach
                                </select>

                                <label>Biaya Pelatihan</label>
                                
                                <input type="text" class="form-control mb-3" placeholder="Biaya Pelatihan" name="biaya_pelatihan">
                            </div>
                            <div class="col-sm">
                                <label>Jadwal</label>
                                <input type="date" class="form-control mb-3" placeholder="jadwal" name="jadwal" readonly>
                                
                                <label>Gambar</label>
                                <input type="file" name="image" class="form-control" placeholder="image">
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-dark w-100 mt-4 mb-0">Tambah</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</main>

@endsection

resources/views/pelatihans/edit.blade.php
@extends('layouts.user_type.auth')

@section('content')

<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card p-4">
                    <div class="col-sm mb-4">
                        <h6>Tambah Pelatihan</h6>
                    </div>
                    <form action="{{ route('pelatihan.update',$pelatihan->id) }}" method="POST" enctype="multipart/form-data"> 
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-sm">
                                <label>Nama Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Nama Pelatihan" name="nm_pelatihan" value="{{ $pelatihan->nm_pelatihan }}" >

                                <?php $pengajars = DB::table('pengajars')
                        ->get(); ?>


                                <label>Nama Pengajar</label>
                                <select class="form-control mb-3" name="kd_pengajar">
                                    @foreach ($pengajars as $pengajar)
                                        <?php if($pengajar->id = $pelatihan->kd_pengajar){ ?>
                                        <option value="{{ $pengajar->id }}" selected>{{ $pengajar->nm_pengajar }}</option>
                                        <?php } else { ?>
                                        <option value="{{ $pengajar->id }}">{{ $pengajar->nm_pengajar }}</option>
                                        <?php } ?>
                                    @endforeach
                                </select>

                                <label>Biaya Pelatihan</label>
                                <input type="text" class="form-control mb-3" placeholder="Biaya Pelatihan" name="biaya_pelatihan" value="{{ $pelatihan->biaya_pelatihan }}" >
                            </div>
                            <div class="col-sm">
                                <label>Jadwal</label>
                                <input type="date" class="form-control mb-3" placeholder="jadwal" name="jadwal" value="{{ $pelatihan->jadwal }}">
                                
                                <label>Gambar</label>
                                <input type="file" name="image" class="form-control" placeholder="image" >
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-dark w-100 mt-4 mb-0">Tambah</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</main>

@endsection

resources/views/pelatihans/index.blade.php
@extends('layouts.user_type.auth')

@section('content')
    <main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4">
                        <div class="container">
                            <div class="row mt-4">
                                <div class="col-sm">
                                    <h6>Daftar Pelajaran </h6>
                                </div>
                                <div class="col-sm-auto">
                                    <a class="btn btn-dark" href="{{ route('pelatihan.create') }}">&plus; Tambah
                                        Pelajaran</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-body px-0 pt-0 pb-2">
                            <div class="table-responsive p-0">
                                <table class="table align-items-center mb-0">
                                    <thead>
                                        <tr>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                                Pelatihan</th>
                                            <th
                                                class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                                Pengajar</th>
                                            <th
                                                class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                                Biaya</th>
                                            <th
                                                class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                                Pengaturan</th>
                                            <th class="text-secondary opacity-7"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($pelatihans as $pelatihan)
                                            <tr>
                                                <td>
                                                    <div class="d-flex px-2 py-1">
                                                        <div>
                                                            <img src="/image/{{ $pelatihan->image }}"
                                                                class="avatar avatar-sm me-3" alt="user1">
                                                        </div>
                                                        <div class="d-flex flex-column justify-content-center">
                                                            <h6 class="mb-0 text-sm">{{ $pelatihan->nm_pelatihan }}</h6>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <p class="text-xs font-weight-bold mb-0">{{ $pelatihan->nm_pengajar }}
                                                    </p>
                                                </td>
                                                <td class="align-middle text-center text-sm">
                                                    <p class="text-xs font-weight-bold mb-0">
                                                        {{ $pelatihan->biaya_pelatihan }}</p>
                                                </td>
                                                <td class="align-middle text-center">
                                                    <form action="{{ route('pelatihan.destroy', $pelatihan->id) }}"
                                                        method="POST">
                                                        <a class="btn btn-primary shadow-none text-dark"
                                                            href="{{ route('pelatihan.edit', $pelatihan->id) }}"
                                                            style="width:60px;">Edit</a>

                                                        @csrf
                                                        @method('DELETE')

                                                        <button type="submit"
                                                            class=" btn btn-primary shadow-none text-danger"
                                                            style="margin-left:20px;">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="12" class="text-danger text-center align-middle py-3 px-5">
                                                    Tidak ada data
                                                </td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection